Allow rails 5 name space
DJOGlobal/declarative_authorization pull request #1
Opened 2021-07-28 19:33 UTC by machipeddy9

https://github.com/DJOGlobal/declarative_authorization/compare/master...DJOGlobal:allow_rails_5_name_space?expand=1

Currently the can? method as defined in ApplicationController allows you to pass namespace: true, which prefixes the permission given with admin_ or manage_ depending on which namespace you're working in.

We need to port this functionality into permitted_to? because it's useful functionality and we use permitted_to? a lot more than can?.

Potential next card: Then you will be able to remove all the duplicate rules in authorization_rules that don't begin with a namespace. Not for this card.

Either monkey-patch the method or fork the gem.

2021-08-02 17:11 UTC, caitlindouglas commented
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer I want to fix the pentest XSS findings so that we are secure](https://trello.com/c/lHvBzjoA/2888-as-a-developer-i-want-to-fix-the-pentest-xss-findings-so-that-we-are-secure)

2021-08-02 17:12 UTC, caitlindouglas commented
@machipeddy9 can you resolve the conflict please?

2021-08-02 17:16 UTC, caitlindouglas commented
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer I want to Extend permitted_to? to include namespaces (admin, manage)](https://trello.com/c/XUmrpUGt/2909-as-a-developer-i-want-to-extend-permittedto-to-include-namespaces-admin-manage)

2021-08-02 20:07 UTC, nclark commented
@caitlindouglas @machipeddy9 is this supposed to have 77 commits dating back to 2016? Can I change the base to `allow_rails_5`?

2021-08-02 20:08 UTC, nclark commented
Or maybe we should merge `allow_rails_5` into master and merge this PR into master as well and take the branch name out of the motionmd Gemfile? I think that would be my preference but not a strong one.

2021-08-02 20:21 UTC, machipeddy9 commented
Hi @nclark I think we should merge allow_rails_5 into master and merge this PR into master. Then we can remove this part  branch: 'allow_rails_5' Gemfile. Thats what I thought?

2021-08-03 19:45 UTC, nclark commented
@machipeddy9 that makes sense to me, can we get that done in another PR? I'd like to review this one with just what's in it.

2021-08-04 15:01 UTC, caitlindouglas commented
@machipeddy9 can you please open a PR for the allow_rails_5 so we can get that merged?

2021-08-04 15:49 UTC, machipeddy9 commented
Hi @caitlindouglas just created the PR for allow_rails_5 branch.
https://github.com/DJOGlobal/declarative_authorization/pull/2

2021-08-04 16:36 UTC, nclark commented on lib/declarative_authorization/in_controller.rb
> +      permitted_to_without_namespace?(privilege, object_or_sym = nil, options = {}, &block) || !!permitted_to_without_namespace_valid
I think we can change the order here right, since we've already called the old method with the namespace and have that answer stored in a boolean, it can short circuit without a second call to old method.

```ruby
!!permitted_to_without_namespace_valid || permitted_to_without_namespace?(privilege, object_or_sym = nil, options = {}, &block)
```

also the call that assigns `permitted_to_without_namespace_valid` is one that checks the permission with the namespace, so i don't think the variable name `permitted_to_without_namespace_valid` makes sense. Maybe change to `permitted_to_with_namespace` or `is_permitted_with_namespace` or something similar. Or even pull that out into another method...

```ruby
def permitted_to_with_namespace?(privilege, object_or_sym = nil, options = {}, &block)
  if object_or_sym.is_a?(Symbol)
    privilege_with_namespace = "#{current_namespace.namespace}_#{privilege}".to_sym

    permitted_to_without_namespace?(privilege_with_namespace, object_or_sym = nil, options = {}, &block) 
  else
    false
  end
end

def permitted_to?(privilege, object_or_sym = nil, options = {}, &block)
  permitted_to_without_namespace?(privilege, object_or_sym = nil, options = {}, &block) || 
    permitted_to_with_namespace?(privilege, object_or_sym = nil, options = {}, &block)
end
```

👆 that seems cleanest to me. what do you think?

2021-08-04 16:58 UTC, machipeddy9 commented on lib/declarative_authorization/in_controller.rb
> +      permitted_to_without_namespace?(privilege, object_or_sym = nil, options = {}, &block) || !!permitted_to_without_namespace_valid
Hi @nclark for sure it is cleanest. I will update it. Thanks for the better approach.

2021-08-04 17:06 UTC, nclark requested changes
Thanks Rakesh. Did you verify it still works as expected in MotionMD?

Also, I've been thinking about it more, and there's something else that's not quite right with this. `declarative_authorization` is a separate gem that we forked and modify and use only in MotionMD, which is already a little weird but you gotta do what you gotta do. But as a separate gem in a separate repo, it's not quite sitting right with me to just have a bare reference to `current_namespace` sitting in this `#permitted_to_with_namespace?` method.

I'm not 100% sure how this will get used but `#current_namespace` is a method in the MotionMD application controller. I believe it will always be set. But there's this separation of concerns where this is a different project entirely. 

I'd like to see `#permitted_to?` modified here to look for a namespace passed into the `options` hash, and `#permitted_to_with_namespace?` can check for it there. That way it can be passed _from_ MotionMD _to_ declarative_authorization instead of just assumed to be there.

Any thoughts on this? I'm curious to hear what @tb0yd thinks as well.

2021-08-04 17:24 UTC, machipeddy9 commented
Hi @nclark Tested with couple of roles on the new changes and working as expected.

2021-08-06 15:41 UTC, machipeddy9 commented
Closing this PR because this logic should be handled through motion md its through monkey_patch.

2021-08-06 15:41 UTC, closed without merging